
// generated by "file2string.go"; DO NOT EDIT

// command: "file2string.go -src index.html -dst=_test.go -var=page -pkg=tilegamecli"

package tilegamecli

const page = `<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>GameCore Terminal</title>
	<meta name="description" content="Terminal for sending commands over a websockets connection.">
</head>
<body>
<h1> Websocket Terminal</h1>
<p>Hello there! Send a command with <code>ws.send()</code> in your web console, or enter a command in the input box. </p>
<h2>Command Terminal</h2>
<pre id="log"></pre>
<form id="cmdform">
	<input id="cmdterm" type="text" placeholder="Type Command" autocomplete="off">
	<input type="submit" value="Send Command">
</form>
<script>
let ws = new WebSocket("ws://" + location.host + "/ws");
let logger = document.querySelector('#log');
let cmdterm = document.querySelector('#cmdterm');
let cmdform = document.querySelector('#cmdform');
cmdform.onsubmit = (e)=> {
	if (cmdterm.value == "") {return false;}
	if (!ws) {return false;}
	logger.innerText += ` + "`" + `${cmdterm.value}` + "`" + ` + "\n";
	ws.send(cmdterm.value);
	cmdterm.value = "";
	cmdterm.focus(); 
	return false;
};
ws.onmessage = (e)=> {
	console.log(e.data);
	logger.innerText += e.data;
	logger.scrollTop = logger.scrollHeight;
};
console.log(ws);
</script>
<style>
#log {
	min-height: 20em;
	height: 20em;
	min-height: 20em;
	resize: vertical;
	background: #eee;
	whitespace: nowrap-pre;
	border: solid 1px gray;
	overflow: auto;
}
</style>
</body>
</html>
`